import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import textwrap
from io import BytesIO, StringIO
from matplotlib.ticker import AutoMinorLocator, MultipleLocator

# ---------- COLOR PALETTES ----------
PALETTES = {
    "Classic TriNetX": ["#8e44ad", "#27ae60"],
    "University of California": ["#1295D8", "#FFB511"],
    "Colorblind-safe": ["#0072B2", "#D55E00"],
    "Tol (bright)": ["#4477AA", "#EE6677"],
    "Blue-Green": ["#1B9E77", "#7570B3"],
    "Red-Green": ["#D7263D", "#21A179"],
    "High-Contrast": ["#000000", "#E69F00"],
    "Grayscale": ["#888888", "#BBBBBB"],
}

CANONICAL_COLS = [
    "Outcome Name",
    "Cohort 1 Risk (%)",
    "Cohort 2 Risk (%)",
    "Cohort 1 Lower 95% CI (%)",
    "Cohort 1 Upper 95% CI (%)",
    "Cohort 2 Lower 95% CI (%)",
    "Cohort 2 Upper 95% CI (%)",
    "P Value",
    "Significant",
]

st.set_page_config(page_title="2-Cohort Outcome Bar Chart", layout="centered")

st.title("Two-Cohort Outcome Bar Chart")
st.markdown("""
Enter outcome risks manually or upload TriNetX Measures of Association exports.  
This version imports the standard **MOA table** format with a `Cohort Statistics` section, automatically calculates cohort risk percentages and 95% confidence intervals for the risk estimates, and includes customizable axis labels and text-collision avoidance.
""")


def initialize_data():
    return pd.DataFrame({
        "Outcome Name": ["Example Outcome"],
        "Cohort 1 Risk (%)": [0.0072],
        "Cohort 2 Risk (%)": [0.0117],
        "Cohort 1 Lower 95% CI (%)": [0.0056],
        "Cohort 1 Upper 95% CI (%)": [0.0092],
        "Cohort 2 Lower 95% CI (%)": [0.0096],
        "Cohort 2 Upper 95% CI (%)": [0.0143],
        "P Value": [0.0210],
        "Significant": [True],
    })


def blank_data():
    return pd.DataFrame(columns=CANONICAL_COLS)


def clean_title_from_filename(filename: str) -> str:
    if not filename:
        return "Uploaded Outcome"
    stem = filename.rsplit("/", 1)[-1].rsplit(".", 1)[0]
    for token in ["_MOA_table", "MOA_table", "_MOA_graph", "MOA_graph", "_table", "table", "_graph", "graph"]:
        stem = stem.replace(token, "")
    stem = stem.replace("_", " ").replace("-", " ").strip()
    return " ".join(stem.split()) or "Uploaded Outcome"


def read_uploaded_text(uploaded_file) -> str:
    uploaded_file.seek(0)
    raw = uploaded_file.read()
    if isinstance(raw, str):
        return raw
    for enc in ["utf-8-sig", "utf-8", "latin-1"]:
        try:
            return raw.decode(enc)
        except UnicodeDecodeError:
            continue
    return raw.decode("utf-8", errors="replace")


def line_label(line: str) -> str:
    return line.strip().strip('"').strip().lower()


def read_section_after_label_csv(text: str, section_label: str) -> pd.DataFrame | None:
    """Read a CSV table immediately below a named TriNetX section label."""
    lines = text.splitlines()
    start_idx = None
    section_label_norm = section_label.lower()

    for i, line in enumerate(lines):
        if line_label(line) == section_label_norm:
            start_idx = i + 1
            break

    if start_idx is None:
        return None

    table_lines = []
    for line in lines[start_idx:]:
        cleaned = line.strip()
        label = line_label(line)
        if not cleaned or label in {" ", ""}:
            if table_lines:
                break
            continue
        # Stop when the next named TriNetX section begins.
        if table_lines and label in {
            "notes", "cohort statistics", "risk difference", "risk ratio", "odds ratio",
            "hazard ratio", "graph data table", "generated by trinetx"
        }:
            break
        table_lines.append(line)

    if not table_lines:
        return None
    return pd.read_csv(StringIO("\n".join(table_lines)))


def find_column(df: pd.DataFrame, candidates: list[str]) -> str | None:
    lower_to_original = {str(c).strip().lower(): str(c).strip() for c in df.columns}
    compact_to_original = {
        str(c).strip().replace(" ", "").replace("_", "").replace("-", "").replace(".", "").replace("%", "percent").lower(): str(c).strip()
        for c in df.columns
    }
    for candidate in candidates:
        direct = candidate.strip().lower()
        compact = candidate.strip().replace(" ", "").replace("_", "").replace("-", "").replace(".", "").replace("%", "percent").lower()
        if direct in lower_to_original:
            return lower_to_original[direct]
        if compact in compact_to_original:
            return compact_to_original[compact]
    return None


def pct_or_nan(value):
    numeric = pd.to_numeric(value, errors="coerce")
    if pd.isna(numeric):
        return np.nan
    return float(numeric) * 100


def wilson_ci_percent(events, n, z=1.959963984540054):
    """Wilson score 95% CI for a binomial proportion, returned as percentages."""
    events = pd.to_numeric(events, errors="coerce")
    n = pd.to_numeric(n, errors="coerce")
    if pd.isna(events) or pd.isna(n) or n <= 0:
        return np.nan, np.nan
    p = max(0.0, min(1.0, float(events) / float(n)))
    denom = 1 + (z**2 / n)
    center = (p + z**2 / (2 * n)) / denom
    half_width = (z * np.sqrt((p * (1 - p) / n) + (z**2 / (4 * n**2)))) / denom
    lower = max(0.0, center - half_width) * 100
    upper = min(1.0, center + half_width) * 100
    return lower, upper


def parse_cohort_statistics_table(cohort_df: pd.DataFrame, filename: str, outcome_name: str | None = None) -> tuple[pd.DataFrame, dict]:
    cohort_df.columns = [str(c).strip() for c in cohort_df.columns]

    cohort_col = find_column(cohort_df, ["Cohort"])
    name_col = find_column(cohort_df, ["Cohort Name", "CohortName"])
    n_col = find_column(cohort_df, ["Patients in Cohort", "PatientsInCohort", "N", "Total"])
    event_col = find_column(cohort_df, ["Patients with Outcome", "PatientsWithOutcome", "Events", "Outcome Count"])
    risk_col = find_column(cohort_df, ["Risk", "Risk %", "Risk Percent"])

    missing = []
    for label, col in {
        "Cohort": cohort_col,
        "Cohort Name": name_col,
        "Patients in Cohort": n_col,
        "Patients with Outcome": event_col,
        "Risk": risk_col,
    }.items():
        if col is None:
            missing.append(label)
    if missing:
        raise ValueError("Missing required Cohort Statistics columns: " + ", ".join(missing))

    cohort_df = cohort_df.copy()
    cohort_df[cohort_col] = pd.to_numeric(cohort_df[cohort_col], errors="coerce")
    cohort_df[n_col] = pd.to_numeric(cohort_df[n_col], errors="coerce")
    cohort_df[event_col] = pd.to_numeric(cohort_df[event_col], errors="coerce")
    cohort_df[risk_col] = pd.to_numeric(cohort_df[risk_col], errors="coerce")
    cohort_df = cohort_df.dropna(subset=[cohort_col, n_col, event_col, risk_col]).sort_values(cohort_col)

    if len(cohort_df) < 2:
        raise ValueError("The Cohort Statistics section must contain two cohort rows.")

    c1 = cohort_df.iloc[0]
    c2 = cohort_df.iloc[1]
    c1_lower, c1_upper = wilson_ci_percent(c1[event_col], c1[n_col])
    c2_lower, c2_upper = wilson_ci_percent(c2[event_col], c2[n_col])

    row = pd.DataFrame({
        "Outcome Name": [outcome_name or clean_title_from_filename(filename)],
        "Cohort 1 Risk (%)": [pct_or_nan(c1[risk_col])],
        "Cohort 2 Risk (%)": [pct_or_nan(c2[risk_col])],
        "Cohort 1 Lower 95% CI (%)": [c1_lower],
        "Cohort 1 Upper 95% CI (%)": [c1_upper],
        "Cohort 2 Lower 95% CI (%)": [c2_lower],
        "Cohort 2 Upper 95% CI (%)": [c2_upper],
    })
    meta = {
        "cohort1_name": str(c1[name_col]).strip() or "Cohort 1",
        "cohort2_name": str(c2[name_col]).strip() or "Cohort 2",
    }
    return row, meta


def parse_graph_data_table(graph_df: pd.DataFrame, filename: str, outcome_name: str | None = None) -> tuple[pd.DataFrame, dict]:
    graph_df.columns = [str(c).strip() for c in graph_df.columns]
    cohort_col = find_column(graph_df, ["Cohort"])
    name_col = find_column(graph_df, ["CohortName", "Cohort Name"])
    risk_col = find_column(graph_df, ["Risk", "Risk %", "Risk Percent"])
    lower_ci_col = find_column(graph_df, [
        "Lower 95% CI", "Lower 95 % CI", "Lower95CI", "Lower CI", "Risk Lower 95% CI",
        "95% CI Lower", "CI Lower", "Lower Confidence Interval", "LCL", "Lower"
    ])
    upper_ci_col = find_column(graph_df, [
        "Upper 95% CI", "Upper 95 % CI", "Upper95CI", "Upper CI", "Risk Upper 95% CI",
        "95% CI Upper", "CI Upper", "Upper Confidence Interval", "UCL", "Upper"
    ])
    if not all([cohort_col, name_col, risk_col]):
        raise ValueError("Missing required Graph Data Table columns: Cohort, CohortName, Risk")

    graph_df = graph_df.copy()
    graph_df[cohort_col] = pd.to_numeric(graph_df[cohort_col], errors="coerce")
    graph_df[risk_col] = pd.to_numeric(graph_df[risk_col], errors="coerce")
    if lower_ci_col:
        graph_df[lower_ci_col] = pd.to_numeric(graph_df[lower_ci_col], errors="coerce")
    if upper_ci_col:
        graph_df[upper_ci_col] = pd.to_numeric(graph_df[upper_ci_col], errors="coerce")
    graph_df = graph_df.dropna(subset=[cohort_col, risk_col]).sort_values(cohort_col)
    if len(graph_df) < 2:
        raise ValueError("Graph Data Table must contain two cohort rows.")

    c1 = graph_df.iloc[0]
    c2 = graph_df.iloc[1]
    row = pd.DataFrame({
        "Outcome Name": [outcome_name or clean_title_from_filename(filename)],
        "Cohort 1 Risk (%)": [pct_or_nan(c1[risk_col])],
        "Cohort 2 Risk (%)": [pct_or_nan(c2[risk_col])],
        "Cohort 1 Lower 95% CI (%)": [pct_or_nan(c1[lower_ci_col]) if lower_ci_col else np.nan],
        "Cohort 1 Upper 95% CI (%)": [pct_or_nan(c1[upper_ci_col]) if upper_ci_col else np.nan],
        "Cohort 2 Lower 95% CI (%)": [pct_or_nan(c2[lower_ci_col]) if lower_ci_col else np.nan],
        "Cohort 2 Upper 95% CI (%)": [pct_or_nan(c2[upper_ci_col]) if upper_ci_col else np.nan],
    })
    meta = {
        "cohort1_name": str(c1[name_col]).strip() or "Cohort 1",
        "cohort2_name": str(c2[name_col]).strip() or "Cohort 2",
    }
    return row, meta


def parse_risk_difference_pvalue(risk_df: pd.DataFrame) -> float:
    risk_df = risk_df.copy()
    risk_df.columns = [str(c).strip() for c in risk_df.columns]
    p_col = find_column(risk_df, ["p", "P", "P Value", "P-Value", "PValue"])
    if p_col is None or risk_df.empty:
        return np.nan
    value = pd.to_numeric(risk_df[p_col], errors="coerce")
    return float(value.iloc[0]) if len(value) and pd.notna(value.iloc[0]) else np.nan


def infer_significant_series(df: pd.DataFrame, alpha: float = 0.05) -> pd.Series:
    pvals = pd.to_numeric(df.get("P Value", np.nan), errors="coerce")
    sig = df.get("Significant", False)
    if isinstance(sig, pd.Series):
        sig_series = sig.fillna(False).astype(bool)
    else:
        sig_series = pd.Series([bool(sig)] * len(df), index=df.index)
    p_sig = pvals.lt(alpha).fillna(False) if isinstance(pvals, pd.Series) else pd.Series([False] * len(df), index=df.index)
    return sig_series | p_sig


def nice_tick_interval(max_value: float) -> float:
    max_value = float(max_value) if pd.notna(max_value) else 1.0
    if max_value <= 0:
        return 1.0
    rough = max_value / 5.0
    exponent = np.floor(np.log10(rough)) if rough > 0 else 0
    fraction = rough / (10 ** exponent) if rough > 0 else 1
    if fraction <= 1:
        nice_fraction = 1
    elif fraction <= 2:
        nice_fraction = 2
    elif fraction <= 2.5:
        nice_fraction = 2.5
    elif fraction <= 5:
        nice_fraction = 5
    else:
        nice_fraction = 10
    return float(nice_fraction * (10 ** exponent))


def extract_section_from_excel(uploaded_file, section_label: str) -> pd.DataFrame | None:
    uploaded_file.seek(0)
    sheets = pd.read_excel(uploaded_file, sheet_name=None, header=None)
    target = section_label.lower()
    stop_labels = {
        "notes", "cohort statistics", "risk difference", "risk ratio", "odds ratio",
        "hazard ratio", "graph data table", "generated by trinetx"
    }
    for _, raw in sheets.items():
        raw = raw.dropna(how="all").dropna(axis=1, how="all")
        for i in range(len(raw)):
            vals = [str(x).strip().strip('"').lower() for x in raw.iloc[i].tolist() if pd.notna(x)]
            if len(vals) == 1 and vals[0] == target:
                # First non-empty row after the section label is header.
                header_idx = None
                for j in range(i + 1, len(raw)):
                    if raw.iloc[j].notna().any():
                        header_idx = j
                        break
                if header_idx is None:
                    return None
                header = [str(x).strip() for x in raw.iloc[header_idx].tolist()]
                rows = []
                for k in range(header_idx + 1, len(raw)):
                    row = raw.iloc[k]
                    vals_k = [str(x).strip().strip('"').lower() for x in row.tolist() if pd.notna(x)]
                    if not row.notna().any():
                        if rows:
                            break
                        continue
                    if rows and len(vals_k) == 1 and vals_k[0] in stop_labels:
                        break
                    rows.append(row.tolist())
                if not rows:
                    return None
                table = pd.DataFrame(rows, columns=header).dropna(how="all")
                table = table.loc[:, [str(c).strip() not in {"", "nan", "None"} for c in table.columns]]
                return table
    return None


def parse_trinetx_export(uploaded_file, outcome_name: str | None = None) -> tuple[pd.DataFrame, dict, str]:
    filename = getattr(uploaded_file, "name", "")
    suffix = filename.lower().rsplit(".", 1)[-1] if "." in filename else "csv"

    def attach_significance(row: pd.DataFrame, risk_diff_df: pd.DataFrame | None):
        p_value = parse_risk_difference_pvalue(risk_diff_df) if risk_diff_df is not None else np.nan
        row = row.copy()
        row["P Value"] = p_value
        row["Significant"] = bool(pd.notna(p_value) and float(p_value) < 0.05)
        return row

    if suffix in ["xlsx", "xls"]:
        cohort_df = extract_section_from_excel(uploaded_file, "Cohort Statistics")
        graph_df = extract_section_from_excel(uploaded_file, "Graph Data Table")
        risk_diff_df = extract_section_from_excel(uploaded_file, "Risk Difference")
        if cohort_df is not None:
            row, meta = parse_cohort_statistics_table(cohort_df, filename, outcome_name)
            row = attach_significance(row, risk_diff_df)
            return row, meta, "Cohort Statistics table with Wilson 95% CIs"
        if graph_df is not None:
            row, meta = parse_graph_data_table(graph_df, filename, outcome_name)
            row = attach_significance(row, risk_diff_df)
            return row, meta, "Graph Data Table"
        raise ValueError("Could not find either a Cohort Statistics section or a Graph Data Table section.")

    text = read_uploaded_text(uploaded_file)
    cohort_df = read_section_after_label_csv(text, "Cohort Statistics")
    graph_df = read_section_after_label_csv(text, "Graph Data Table")
    risk_diff_df = read_section_after_label_csv(text, "Risk Difference")
    if cohort_df is not None:
        row, meta = parse_cohort_statistics_table(cohort_df, filename, outcome_name)
        row = attach_significance(row, risk_diff_df)
        return row, meta, "Cohort Statistics table with Wilson 95% CIs"
    if graph_df is not None:
        row, meta = parse_graph_data_table(graph_df, filename, outcome_name)
        row = attach_significance(row, risk_diff_df)
        return row, meta, "Graph Data Table"

    # Fallback: allow direct CSV table import if it already starts with headers.
    fallback_df = pd.read_csv(StringIO(text))
    try:
        row, meta = parse_cohort_statistics_table(fallback_df, filename, outcome_name)
        row = attach_significance(row, risk_diff_df)
        return row, meta, "direct Cohort Statistics table with Wilson 95% CIs"
    except Exception:
        row, meta = parse_graph_data_table(fallback_df, filename, outcome_name)
        row = attach_significance(row, risk_diff_df)
        return row, meta, "direct Graph Data Table"


def coerce_app_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    if df is None or len(df.columns) == 0:
        return blank_data()
    df = df.copy()
    if "Outcome Name" not in df.columns and len(df.columns) >= 1:
        df = df.rename(columns={df.columns[0]: "Outcome Name"})
    if "Cohort 1 Risk (%)" not in df.columns and len(df.columns) >= 2:
        df = df.rename(columns={df.columns[1]: "Cohort 1 Risk (%)"})
    if "Cohort 2 Risk (%)" not in df.columns and len(df.columns) >= 3:
        df = df.rename(columns={df.columns[2]: "Cohort 2 Risk (%)"})
    for col in CANONICAL_COLS:
        if col not in df.columns:
            if col == "Outcome Name":
                df[col] = ""
            elif col == "Significant":
                df[col] = False
            else:
                df[col] = np.nan
    df = df[CANONICAL_COLS]
    numeric_cols = [c for c in CANONICAL_COLS if c not in {"Outcome Name", "Significant"}]
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")
    df["Significant"] = df["Significant"].apply(lambda x: str(x).strip().lower() in {"true", "1", "yes", "y"} if pd.notna(x) and not isinstance(x, bool) else bool(x)).fillna(False)
    df["Outcome Name"] = df["Outcome Name"].astype(str)
    return df.dropna(subset=["Outcome Name", "Cohort 1 Risk (%)", "Cohort 2 Risk (%)"], how="all")


# ---------- SESSION STATE ----------
if "data" not in st.session_state:
    st.session_state.data = initialize_data()
if "cohort1_name" not in st.session_state:
    st.session_state.cohort1_name = "Cohort 1"
if "cohort2_name" not in st.session_state:
    st.session_state.cohort2_name = "Cohort 2"
if "last_import_summary" not in st.session_state:
    st.session_state.last_import_summary = ""

# ---------- IMPORT CONTROLS ----------
st.sidebar.header("Import TriNetX Data Sheets")
uploaded_files = st.sidebar.file_uploader(
    "Upload one or more MOA table or graph exports",
    type=["csv", "xlsx", "xls"],
    accept_multiple_files=True,
    help="Use the TriNetX Measures of Association table export with a Cohort Statistics section. The app imports Risk and calculates Wilson 95% confidence intervals from Patients in Cohort and Patients with Outcome. Graph Data Table exports are also supported.",
)

import_mode = st.sidebar.radio("When importing", ["Replace current table", "Append to current table"], index=0)

if st.sidebar.button("Import TriNetX data", disabled=not uploaded_files):
    imported_rows = []
    import_errors = []
    imported_meta = None
    import_sources = []

    for uploaded in uploaded_files:
        try:
            row, meta, source = parse_trinetx_export(uploaded)
            imported_rows.append(row)
            imported_meta = imported_meta or meta
            import_sources.append(f"{uploaded.name}: {source}")
        except Exception as exc:
            import_errors.append(f"{uploaded.name}: {exc}")

    if imported_rows:
        imported_df = pd.concat(imported_rows, ignore_index=True)
        if import_mode == "Append to current table":
            st.session_state.data = pd.concat([coerce_app_dataframe(st.session_state.data), imported_df], ignore_index=True)
        else:
            st.session_state.data = imported_df

        if imported_meta:
            st.session_state.cohort1_name = imported_meta["cohort1_name"]
            st.session_state.cohort2_name = imported_meta["cohort2_name"]

        st.session_state.last_import_summary = "Imported " + str(len(imported_rows)) + " file(s):\n" + "\n".join(import_sources)
        st.sidebar.success(f"Imported {len(imported_rows)} file(s).")

    if import_errors:
        st.sidebar.error("Some files could not be imported:\n" + "\n".join(import_errors))

if st.sidebar.button("Reset example data"):
    st.session_state.data = initialize_data()
    st.session_state.cohort1_name = "Cohort 1"
    st.session_state.cohort2_name = "Cohort 2"
    st.session_state.last_import_summary = ""

# ---------- SIDEBAR: GRAPH SETTINGS ----------
st.sidebar.header("Graph Settings")
cohort1_name = st.sidebar.text_input("Cohort 1 Name", st.session_state.cohort1_name, key="cohort1_name_input")
cohort2_name = st.sidebar.text_input("Cohort 2 Name", st.session_state.cohort2_name, key="cohort2_name_input")
st.session_state.cohort1_name = cohort1_name
st.session_state.cohort2_name = cohort2_name

palette_name = st.sidebar.selectbox("Color Palette", list(PALETTES.keys()), index=1)
color1_default, color2_default = PALETTES[palette_name]
color1 = st.sidebar.color_picker(f"Bar Color for {cohort1_name}", color1_default)
color2 = st.sidebar.color_picker(f"Bar Color for {cohort2_name}", color2_default)

# ---------- EDITOR ----------
df = coerce_app_dataframe(st.session_state.data)
display_df = df.rename(columns={
    "Cohort 1 Risk (%)": f"{cohort1_name} Risk (%)",
    "Cohort 2 Risk (%)": f"{cohort2_name} Risk (%)",
    "Cohort 1 Lower 95% CI (%)": f"{cohort1_name} Lower 95% CI (%)",
    "Cohort 1 Upper 95% CI (%)": f"{cohort1_name} Upper 95% CI (%)",
    "Cohort 2 Lower 95% CI (%)": f"{cohort2_name} Lower 95% CI (%)",
    "Cohort 2 Upper 95% CI (%)": f"{cohort2_name} Upper 95% CI (%)",
    "P Value": "P Value",
    "Significant": "Significant Difference?",
})

st.subheader("Outcome Data")
if st.session_state.last_import_summary:
    st.caption(st.session_state.last_import_summary)

edited_display_df = st.data_editor(
    display_df,
    num_rows="dynamic",
    use_container_width=True,
    column_config={
        "Outcome Name": st.column_config.TextColumn("Outcome Name"),
        f"{cohort1_name} Risk (%)": st.column_config.NumberColumn(f"{cohort1_name} Risk (%)", min_value=0.0, max_value=100.0, step=0.0001, format="%.6f"),
        f"{cohort2_name} Risk (%)": st.column_config.NumberColumn(f"{cohort2_name} Risk (%)", min_value=0.0, max_value=100.0, step=0.0001, format="%.6f"),
        f"{cohort1_name} Lower 95% CI (%)": st.column_config.NumberColumn(f"{cohort1_name} Lower 95% CI (%)", min_value=0.0, max_value=100.0, step=0.0001, format="%.6f"),
        f"{cohort1_name} Upper 95% CI (%)": st.column_config.NumberColumn(f"{cohort1_name} Upper 95% CI (%)", min_value=0.0, max_value=100.0, step=0.0001, format="%.6f"),
        f"{cohort2_name} Lower 95% CI (%)": st.column_config.NumberColumn(f"{cohort2_name} Lower 95% CI (%)", min_value=0.0, max_value=100.0, step=0.0001, format="%.6f"),
        f"{cohort2_name} Upper 95% CI (%)": st.column_config.NumberColumn(f"{cohort2_name} Upper 95% CI (%)", min_value=0.0, max_value=100.0, step=0.0001, format="%.6f"),
        "P Value": st.column_config.NumberColumn("P Value", min_value=0.0, max_value=1.0, step=0.0001, format="%.6f"),
        "Significant Difference?": st.column_config.CheckboxColumn("Significant Difference?"),
    },
    key="data_editor",
)

edited_df = edited_display_df.rename(columns={
    f"{cohort1_name} Risk (%)": "Cohort 1 Risk (%)",
    f"{cohort2_name} Risk (%)": "Cohort 2 Risk (%)",
    f"{cohort1_name} Lower 95% CI (%)": "Cohort 1 Lower 95% CI (%)",
    f"{cohort1_name} Upper 95% CI (%)": "Cohort 1 Upper 95% CI (%)",
    f"{cohort2_name} Lower 95% CI (%)": "Cohort 2 Lower 95% CI (%)",
    f"{cohort2_name} Upper 95% CI (%)": "Cohort 2 Upper 95% CI (%)",
    "Significant Difference?": "Significant",
})
st.session_state.data = coerce_app_dataframe(edited_df)
df = st.session_state.data.copy()

# ---------- CHART CONTROLS ----------
st.sidebar.header("Chart Appearance")
orientation = st.sidebar.radio("Bar Orientation", ["Vertical", "Horizontal"], index=1)
default_x_axis_label = "Outcome" if orientation == "Vertical" else "Risk (%)"
default_y_axis_label = "Risk (%)" if orientation == "Vertical" else "Outcome"
x_axis_label = st.sidebar.text_input("X-axis Label", default_x_axis_label)
y_axis_label = st.sidebar.text_input("Y-axis Label", default_y_axis_label)
font_family = st.sidebar.selectbox("Font Family", ["Arial", "Helvetica", "Times New Roman", "Courier New", "Verdana"], index=0)
font_size = st.sidebar.slider("Font Size", 8, 32, 14)
tick_fontsize = st.sidebar.slider("Tick Mark Font Size", 6, 28, 11)
auto_avoid_text_collisions = st.sidebar.checkbox("Automatically avoid text collisions", value=True, help="Wraps long outcome labels, expands plot limits for value labels, and uses conservative margins so labels, error bars, and legends do not overlap.")
wrap_outcome_labels = st.sidebar.checkbox("Wrap long outcome labels", value=True)
max_label_chars = st.sidebar.slider("Max characters per outcome-label line", 8, 40, 18)
vertical_tick_rotation = st.sidebar.slider("Vertical-chart outcome label rotation", 0, 90, 30)
major_tick_length = st.sidebar.slider("Major Tick Length", 2, 15, 8)
minor_ticks = st.sidebar.checkbox("Show Minor Ticks", value=True)

bar_width = st.sidebar.slider("Bar Width", 0.1, 0.6, 0.26)
group_gap = st.sidebar.slider("Distance Between Bar Groups", 1.0, 5.0, 2.3, step=0.05)
pair_gap = st.sidebar.slider("Spacing Between Cohort Bars in a Group", 0.05, 1.2, 0.32, step=0.01)
gridlines = st.sidebar.checkbox("Show gridlines", value=True)
show_legend = st.sidebar.checkbox("Show legend", value=True)
show_values = st.sidebar.checkbox("Show values on bars", value=True)
value_decimals = st.sidebar.slider("Value Label Decimals", 2, 6, 4)
show_error_bars = st.sidebar.checkbox("Show 95% CI error bars", value=True, help="Uses lower/upper 95% CI columns imported from TriNetX or entered manually.")
error_bar_capsize = st.sidebar.slider("Error Bar Cap Size", 0, 12, 4)
error_bar_linewidth = st.sidebar.slider("Error Bar Line Width", 0.5, 4.0, 1.4, step=0.1)
show_significance_stars = st.sidebar.checkbox("Add * above significant differences", value=False, help="Adds an asterisk when the row is marked Significant Difference? or when P Value is below the alpha threshold.")
significance_alpha = st.sidebar.number_input("Significance alpha", min_value=0.000001, max_value=1.0, value=0.05, step=0.001, format="%.6f")

st.sidebar.header("Figure Size")
size_unit = st.sidebar.radio("Size Unit", ["Inches", "Pixels"], index=0, horizontal=True)
export_dpi = st.sidebar.number_input(
    "DPI for display/export",
    min_value=72,
    max_value=600,
    value=300,
    step=25,
    help="When Pixels is selected, width and height are converted to inches using this DPI. For example, 1800 px at 300 DPI becomes 6 inches."
)

if size_unit == "Inches":
    figure_width = st.sidebar.number_input("Figure Width (inches)", min_value=2.0, max_value=30.0, value=10.0, step=0.25)
    figure_height = st.sidebar.number_input("Figure Height (inches)", min_value=2.0, max_value=30.0, value=6.0, step=0.25)
    figure_width_inches = float(figure_width)
    figure_height_inches = float(figure_height)
else:
    figure_width_px = st.sidebar.number_input("Figure Width (pixels)", min_value=300, max_value=8000, value=1800, step=100)
    figure_height_px = st.sidebar.number_input("Figure Height (pixels)", min_value=300, max_value=8000, value=1200, step=100)
    figure_width_inches = float(figure_width_px) / float(export_dpi)
    figure_height_inches = float(figure_height_px) / float(export_dpi)

st.sidebar.caption(f"Rendered Matplotlib size: {figure_width_inches:.2f} × {figure_height_inches:.2f} inches at {export_dpi} DPI")

percent_axis_label = "Y-axis" if orientation == "Vertical" else "X-axis"
axis_data_max = pd.concat([
    pd.to_numeric(df["Cohort 1 Risk (%)"], errors="coerce"),
    pd.to_numeric(df["Cohort 2 Risk (%)"], errors="coerce"),
    pd.to_numeric(df["Cohort 1 Upper 95% CI (%)"], errors="coerce"),
    pd.to_numeric(df["Cohort 2 Upper 95% CI (%)"], errors="coerce"),
]).dropna()
suggested_axis_max = float(axis_data_max.max()) if not axis_data_max.empty else 1.0
suggested_axis_max = max(1.0, suggested_axis_max * 1.4)
suggested_tick_interval = nice_tick_interval(suggested_axis_max)

st.sidebar.header("% Axis Settings")
manual_percent_axis = st.sidebar.checkbox(f"Manually set {percent_axis_label} length and intervals", value=False)
percent_axis_min = 0.0
percent_axis_max = suggested_axis_max
percent_axis_tick_interval = suggested_tick_interval
if manual_percent_axis:
    percent_axis_min = st.sidebar.number_input(f"{percent_axis_label} minimum (%)", value=0.0, step=float(max(suggested_tick_interval / 5.0, 0.000001)), format="%.6f")
    percent_axis_max = st.sidebar.number_input(f"{percent_axis_label} maximum (%)", value=float(round(suggested_axis_max, 6)), step=float(max(suggested_tick_interval / 2.0, 0.000001)), format="%.6f")
    percent_axis_tick_interval = st.sidebar.number_input(f"{percent_axis_label} major tick interval (%)", min_value=0.000001, value=float(round(suggested_tick_interval, 6)), step=float(max(suggested_tick_interval / 5.0, 0.000001)), format="%.6f")
    if percent_axis_max <= percent_axis_min:
        st.sidebar.error("The % axis maximum must be greater than the minimum.")

st.subheader("Bar Chart")

if show_error_bars:
    needed_ci_cols = [
        "Cohort 1 Lower 95% CI (%)", "Cohort 1 Upper 95% CI (%)",
        "Cohort 2 Lower 95% CI (%)", "Cohort 2 Upper 95% CI (%)",
    ]
    if df[needed_ci_cols].isna().all(axis=None):
        st.info("Error bars are enabled, but no 95% CI columns are populated. Upload a Cohort Statistics export or enter CI values manually.")

if show_significance_stars:
    if pd.to_numeric(df.get("P Value", np.nan), errors="coerce").isna().all() and not df.get("Significant", pd.Series(False, index=df.index)).astype(bool).any():
        st.info("Significance stars are enabled, but no p-values or manual Significant Difference? flags are populated yet.")


def plot_2cohort_outcomes(
    df, cohort1, cohort2, color1, color2, orientation, font_family, font_size, tick_fontsize,
    bar_width, gridlines, show_values, show_legend, group_gap, pair_gap, major_tick_length, minor_ticks,
    show_error_bars=False, error_bar_capsize=4, error_bar_linewidth=1.4, value_decimals=4,
    figure_width_inches=10.0, figure_height_inches=6.0, x_axis_label="", y_axis_label="",
    auto_avoid_text_collisions=True, wrap_outcome_labels=True, max_label_chars=18, vertical_tick_rotation=30,
    show_significance_stars=False, significance_alpha=0.05,
    manual_percent_axis=False, percent_axis_min=0.0, percent_axis_max=None, percent_axis_tick_interval=None,
):
    df = coerce_app_dataframe(df)
    if len(df) == 0:
        fig, ax = plt.subplots()
        ax.set_title("No data to plot.")
        return fig

    outcomes = df["Outcome Name"].tolist()
    if wrap_outcome_labels:
        display_outcomes = ["\n".join(textwrap.wrap(str(label), width=max_label_chars, break_long_words=False)) or str(label) for label in outcomes]
    else:
        display_outcomes = [str(label) for label in outcomes]

    cohort1_vals = df["Cohort 1 Risk (%)"].fillna(0).astype(float).tolist()
    cohort2_vals = df["Cohort 2 Risk (%)"].fillna(0).astype(float).tolist()
    group_centers = np.arange(len(outcomes)) * group_gap
    pair_offset = pair_gap / 2
    max_val = max(cohort1_vals + cohort2_vals) if cohort1_vals + cohort2_vals else 0.0

    error_cols = [
        "Cohort 1 Lower 95% CI (%)", "Cohort 1 Upper 95% CI (%)",
        "Cohort 2 Lower 95% CI (%)", "Cohort 2 Upper 95% CI (%)",
    ]
    has_error_data = show_error_bars and all(col in df.columns for col in error_cols) and df[error_cols].notna().all(axis=1).any()

    def asymmetric_errors(values, lower_col, upper_col):
        values_arr = np.array(values, dtype=float)
        lower_arr = pd.to_numeric(df[lower_col], errors="coerce").to_numpy(dtype=float)
        upper_arr = pd.to_numeric(df[upper_col], errors="coerce").to_numpy(dtype=float)
        lower_err = np.where(np.isfinite(lower_arr), np.maximum(values_arr - lower_arr, 0), 0)
        upper_err = np.where(np.isfinite(upper_arr), np.maximum(upper_arr - values_arr, 0), 0)
        return np.vstack([lower_err, upper_err])

    def finite_or_value(candidate, fallback):
        try:
            candidate = float(candidate)
            if np.isfinite(candidate):
                return candidate
        except Exception:
            pass
        return float(fallback)

    def upper_anchor(col_name, idx, fallback):
        if has_error_data and col_name in df.columns:
            return finite_or_value(pd.to_numeric(df[col_name], errors="coerce").iloc[idx], fallback)
        return float(fallback)

    max_ci_val = max_val
    if has_error_data:
        ci_upper_values = pd.concat([
            pd.to_numeric(df["Cohort 1 Upper 95% CI (%)"], errors="coerce"),
            pd.to_numeric(df["Cohort 2 Upper 95% CI (%)"], errors="coerce"),
        ]).dropna()
        if not ci_upper_values.empty:
            max_ci_val = max(max_val, float(ci_upper_values.max()))

    annotation_multiplier = 1.32
    if show_values and auto_avoid_text_collisions:
        annotation_multiplier += 0.13
    if show_significance_stars:
        annotation_multiplier += 0.12

    plt.style.use("default")
    fig, ax = plt.subplots(figsize=(max(2.0, float(figure_width_inches)), max(2.0, float(figure_height_inches))))
    fig.patch.set_facecolor("#FAFAFA")
    ax.set_facecolor("#FAFAFA")
    value_fmt = "{:,." + str(value_decimals) + "f}%"
    sig_mask = infer_significant_series(df, alpha=float(significance_alpha))

    if orientation == "Vertical":
        bars1 = ax.bar(group_centers - pair_offset, cohort1_vals, bar_width, label=cohort1, color=color1, linewidth=0, zorder=3)
        bars2 = ax.bar(group_centers + pair_offset, cohort2_vals, bar_width, label=cohort2, color=color2, linewidth=0, zorder=3)
        if has_error_data:
            ax.errorbar(group_centers - pair_offset, cohort1_vals, yerr=asymmetric_errors(cohort1_vals, "Cohort 1 Lower 95% CI (%)", "Cohort 1 Upper 95% CI (%)"), fmt="none", ecolor="black", elinewidth=error_bar_linewidth, capsize=error_bar_capsize, zorder=4)
            ax.errorbar(group_centers + pair_offset, cohort2_vals, yerr=asymmetric_errors(cohort2_vals, "Cohort 2 Lower 95% CI (%)", "Cohort 2 Upper 95% CI (%)"), fmt="none", ecolor="black", elinewidth=error_bar_linewidth, capsize=error_bar_capsize, zorder=4)
        ax.set_xticks(group_centers)
        ax.set_xticklabels(display_outcomes, fontsize=font_size, fontweight="bold", rotation=vertical_tick_rotation, ha="right" if vertical_tick_rotation else "center", fontname=font_family)
        ax.set_ylabel(y_axis_label or "Risk (%)", fontsize=font_size + 3, fontweight="bold", fontname=font_family, labelpad=max(8, font_size // 2))
        ax.set_xlabel(x_axis_label or "Outcome", fontsize=font_size + 2, fontname=font_family, labelpad=max(10, font_size // 2))

        if manual_percent_axis and percent_axis_max is not None:
            ax.set_ylim([float(percent_axis_min), float(percent_axis_max)])
            if percent_axis_tick_interval and float(percent_axis_tick_interval) > 0:
                ax.yaxis.set_major_locator(MultipleLocator(float(percent_axis_tick_interval)))
                if minor_ticks:
                    ax.yaxis.set_minor_locator(AutoMinorLocator())
        else:
            ax.set_ylim([0, max(0.001, max_ci_val * annotation_multiplier)])

        label_positions = []
        offset = max(0.00001, max_ci_val * 0.04 if max_ci_val > 0 else 0.02)
        min_vertical_gap = max(0.00001, max_ci_val * 0.075) if auto_avoid_text_collisions else 0
        star_offset = max(offset * 1.25, max_ci_val * 0.05 if max_ci_val > 0 else 0.03)
        for i, (rect1, rect2) in enumerate(zip(bars1, bars2)):
            h1 = rect1.get_height()
            h2 = rect2.get_height()
            y1 = upper_anchor("Cohort 1 Upper 95% CI (%)", i, h1) + offset
            y2 = upper_anchor("Cohort 2 Upper 95% CI (%)", i, h2) + offset
            if auto_avoid_text_collisions and h1 > 0 and h2 > 0 and abs(y1 - y2) < min_vertical_gap:
                if y1 <= y2:
                    y2 = y1 + min_vertical_gap
                else:
                    y1 = y2 + min_vertical_gap
            label_positions.append((y1, y2))
            if show_values:
                if h1 > 0:
                    ax.text(rect1.get_x() + rect1.get_width() / 2., y1, value_fmt.format(h1), ha="center", va="bottom", fontsize=max(6, font_size - 1), fontweight="medium", fontname=font_family, clip_on=False)
                if h2 > 0:
                    ax.text(rect2.get_x() + rect2.get_width() / 2., y2, value_fmt.format(h2), ha="center", va="bottom", fontsize=max(6, font_size - 1), fontweight="medium", fontname=font_family, clip_on=False)
            if show_significance_stars and bool(sig_mask.iloc[i]):
                star_base = max(y1 if show_values else upper_anchor("Cohort 1 Upper 95% CI (%)", i, h1), y2 if show_values else upper_anchor("Cohort 2 Upper 95% CI (%)", i, h2))
                ax.text(group_centers[i], star_base + star_offset, "*", ha="center", va="bottom", fontsize=font_size + 6, fontweight="bold", fontname=font_family, clip_on=False)

        if gridlines:
            ax.yaxis.grid(True, color="#DDDDDD", zorder=0)
        ax.xaxis.set_tick_params(labelsize=tick_fontsize, length=major_tick_length)
        ax.yaxis.set_tick_params(labelsize=tick_fontsize, length=major_tick_length)
        if minor_ticks and not manual_percent_axis:
            ax.yaxis.set_minor_locator(AutoMinorLocator())
            ax.yaxis.set_tick_params(which="minor", length=int(major_tick_length * 0.7), width=0.8)
    else:
        bars1 = ax.barh(group_centers - pair_offset, cohort1_vals, bar_width, label=cohort1, color=color1, linewidth=0, zorder=3)
        bars2 = ax.barh(group_centers + pair_offset, cohort2_vals, bar_width, label=cohort2, color=color2, linewidth=0, zorder=3)
        if has_error_data:
            ax.errorbar(cohort1_vals, group_centers - pair_offset, xerr=asymmetric_errors(cohort1_vals, "Cohort 1 Lower 95% CI (%)", "Cohort 1 Upper 95% CI (%)"), fmt="none", ecolor="black", elinewidth=error_bar_linewidth, capsize=error_bar_capsize, zorder=4)
            ax.errorbar(cohort2_vals, group_centers + pair_offset, xerr=asymmetric_errors(cohort2_vals, "Cohort 2 Lower 95% CI (%)", "Cohort 2 Upper 95% CI (%)"), fmt="none", ecolor="black", elinewidth=error_bar_linewidth, capsize=error_bar_capsize, zorder=4)
        ax.set_yticks(group_centers)
        ax.set_yticklabels(display_outcomes, fontsize=font_size, fontweight="bold", fontname=font_family)
        ax.set_xlabel(x_axis_label or "Risk (%)", fontsize=font_size + 3, fontweight="bold", fontname=font_family, labelpad=max(8, font_size // 2))
        ax.set_ylabel(y_axis_label or "Outcome", fontsize=font_size + 2, fontname=font_family, labelpad=max(10, font_size // 2))

        if manual_percent_axis and percent_axis_max is not None:
            ax.set_xlim([float(percent_axis_min), float(percent_axis_max)])
            if percent_axis_tick_interval and float(percent_axis_tick_interval) > 0:
                ax.xaxis.set_major_locator(MultipleLocator(float(percent_axis_tick_interval)))
                if minor_ticks:
                    ax.xaxis.set_minor_locator(AutoMinorLocator())
        else:
            ax.set_xlim([0, max(0.001, max_ci_val * annotation_multiplier)])

        offset = max(0.00001, max_ci_val * 0.045 if max_ci_val > 0 else 0.02)
        star_offset = max(offset * 1.3, max_ci_val * 0.06 if max_ci_val > 0 else 0.03)
        for i, rect in enumerate(bars1):
            width_val = rect.get_width()
            if show_values and width_val > 0:
                anchor = upper_anchor("Cohort 1 Upper 95% CI (%)", i, width_val)
                ax.text(anchor + offset, rect.get_y() + rect.get_height() / 2., value_fmt.format(width_val), va="center", ha="left", fontsize=max(6, font_size - 1), fontweight="medium", fontname=font_family, clip_on=False)
        for i, rect in enumerate(bars2):
            width_val = rect.get_width()
            if show_values and width_val > 0:
                anchor = upper_anchor("Cohort 2 Upper 95% CI (%)", i, width_val)
                ax.text(anchor + offset, rect.get_y() + rect.get_height() / 2., value_fmt.format(width_val), va="center", ha="left", fontsize=max(6, font_size - 1), fontweight="medium", fontname=font_family, clip_on=False)
        if show_significance_stars:
            for i in range(len(group_centers)):
                if bool(sig_mask.iloc[i]):
                    base1 = upper_anchor("Cohort 1 Upper 95% CI (%)", i, cohort1_vals[i]) + (offset if show_values else 0)
                    base2 = upper_anchor("Cohort 2 Upper 95% CI (%)", i, cohort2_vals[i]) + (offset if show_values else 0)
                    star_x = max(base1, base2) + star_offset
                    ax.text(star_x, group_centers[i], "*", va="center", ha="left", fontsize=font_size + 6, fontweight="bold", fontname=font_family, clip_on=False)

        if gridlines:
            ax.xaxis.grid(True, color="#DDDDDD", zorder=0)
        ax.xaxis.set_tick_params(labelsize=tick_fontsize, length=major_tick_length)
        ax.yaxis.set_tick_params(labelsize=tick_fontsize, length=major_tick_length)
        if minor_ticks and not manual_percent_axis:
            ax.xaxis.set_minor_locator(AutoMinorLocator())
            ax.xaxis.set_tick_params(which="minor", length=int(major_tick_length * 0.7), width=0.8)

    if show_legend:
        ax.legend(fontsize=font_size + 1, frameon=False, loc="upper left", bbox_to_anchor=(1.01, 1.01), borderaxespad=0)

    for spine in ["top", "right", "left", "bottom"]:
        ax.spines[spine].set_visible(False)

    if auto_avoid_text_collisions:
        if orientation == "Horizontal":
            longest = max([len(str(x)) for x in outcomes] or [0])
            left_margin = min(0.48, max(0.22, 0.10 + 0.010 * longest))
            right_margin = 0.70 if show_legend else (0.82 if (show_values or show_significance_stars) else 0.92)
            fig.subplots_adjust(left=left_margin, right=right_margin, top=0.94, bottom=0.16)
        else:
            longest = max([len(str(x)) for x in outcomes] or [0])
            bottom_margin = min(0.48, max(0.22, 0.08 + 0.012 * longest))
            top_margin = 0.84 if (show_values or show_significance_stars) else 0.92
            right_margin = 0.76 if show_legend else 0.94
            fig.subplots_adjust(left=0.14, right=right_margin, top=top_margin, bottom=bottom_margin)
    else:
        plt.tight_layout(rect=[0, 0, 0.89 if show_legend else 1, 1], pad=1.2)
    return fig


fig = plot_2cohort_outcomes(

    df,
    cohort1=cohort1_name,
    cohort2=cohort2_name,
    color1=color1,
    color2=color2,
    orientation=orientation,
    font_family=font_family,
    font_size=font_size,
    tick_fontsize=tick_fontsize,
    bar_width=bar_width,
    gridlines=gridlines,
    show_values=show_values,
    show_legend=show_legend,
    group_gap=group_gap,
    pair_gap=pair_gap,
    major_tick_length=major_tick_length,
    minor_ticks=minor_ticks,
    show_error_bars=show_error_bars,
    error_bar_capsize=error_bar_capsize,
    error_bar_linewidth=error_bar_linewidth,
    value_decimals=value_decimals,
    figure_width_inches=figure_width_inches,
    figure_height_inches=figure_height_inches,
    x_axis_label=x_axis_label,
    y_axis_label=y_axis_label,
    auto_avoid_text_collisions=auto_avoid_text_collisions,
    wrap_outcome_labels=wrap_outcome_labels,
    max_label_chars=max_label_chars,
    vertical_tick_rotation=vertical_tick_rotation,
    show_significance_stars=show_significance_stars,
    significance_alpha=significance_alpha,
    manual_percent_axis=manual_percent_axis,
    percent_axis_min=percent_axis_min,
    percent_axis_max=percent_axis_max,
    percent_axis_tick_interval=percent_axis_tick_interval,
)

st.pyplot(fig, use_container_width=False)

png_buf = BytesIO()
fig.savefig(png_buf, format="png", dpi=export_dpi, bbox_inches="tight")
st.download_button("📥 Download Chart as PNG", data=png_buf.getvalue(), file_name="2Cohort_Bargraph.png", mime="image/png")

csv_buf = st.session_state.data.to_csv(index=False).encode("utf-8")
st.download_button("📥 Download Edited Data as CSV", data=csv_buf, file_name="2Cohort_Bargraph_Data.csv", mime="text/csv")
